name: flutterworkbench
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^3.0.10                 #一个强大的Http请求库，支持Restful API、FormData、拦截器、请求取消、Cookie管理、文件上传下载、超时等
  flukit: ^1.0.2               #一个常用的Widget库，包括下拉刷新、轮播图、快速滚动条、渐变进度条、城市选择器等
  webview_flutter: ^0.3.22     # WkWebView
  fluttertoast: ^7.0.4         # 加载 提示（官方）
  flutter_easyloading: ^1.1.4  # 加载 提示
  sharesdk_plugin: ^1.2.8      # 分享
  barcode_scan: ^3.0.0         # 扫码(此库发现是Swift 需要在Podfile添加 use_modular_headers! 但是导入还是不能用fack！)
  permission_handler: ^5.0.1+1 # 获取权限 依赖库
  image_gallery_saver: ^1.5.0  #保存图片到本地相册
  qr_flutter: ^3.2.0           # 生成二维码
  #  qrscan: ^0.2.17              #扫描识别二维码、条形码
  flutter_swiper: ^1.1.6       #无限轮播插件
  url_launcher: ^5.5.2         #调用地图
  flutter_map: ^0.10.1+1       #地图
  flutter_tableview: ^1.0.1    #实现Tableview的效果

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/h5/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: appIconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
